### ISSUE TITLE
Module Name

### ISSUE THREAD

**Issue by kaare** [0racle/p6-Net-Netmask#1]
I think it's wonderful to see new p6 modules. But in these ipv6 times, wouldn't it be better to include ip4, ip4, or cidr4 somewhere in the name?

**Comment by 0racle** [comment]
I didn't feel it necessary for a number of reasons. The Perl 5 module of the same name - upon which I based the API - also does IPv4 only. The README unambiguously shows that it only does IPv4.

It also leaves things open for the module to support IPv6 later... Pull request welcome.

**Comment by kaare** [comment]
OK, it's up to you.
I don't think basing the name on an (at least) 18 year old P5 module makes a lot of sense, though. But it's only my opinion.
